/**
 * AgentOps SDK - Audit Report Engine
 *
 * Generates compliance and audit reports for multiple frameworks.
 */

import type {
  AuditReportConfig,
  ComplianceFramework,
  AuditReport,
  ReportSection,
  Control,
  EvidenceItem,
  ComplianceGap,
  CompliancePosture,
  PostureScore,
  AuditDataSource,
  AuditReportMetrics,
} from "./types.js";

interface FrameworkDefinition {
  framework: ComplianceFramework;
  name: string;
  sections: {
    id: string;
    title: string;
    description: string;
    controls: Omit<Control, "status" | "evidence" | "notes">[];
  }[];
}

const FRAMEWORK_DEFINITIONS: FrameworkDefinition[] = [
  {
    framework: "eu_ai_act",
    name: "EU AI Act",
    sections: [
      {
        id: "eu-art-13",
        title: "Article 13 - Transparency",
        description:
          "High-risk AI systems shall be designed to ensure transparency and allow users to interpret outputs.",
        controls: [
          {
            id: "eu-13-1",
            name: "System Documentation",
            description:
              "AI system capabilities, limitations, and intended purpose are documented.",
          },
          {
            id: "eu-13-2",
            name: "Output Interpretability",
            description: "Users can interpret AI system outputs appropriately.",
          },
        ],
      },
      {
        id: "eu-art-14",
        title: "Article 14 - Human Oversight",
        description:
          "High-risk AI systems shall be designed to allow effective human oversight.",
        controls: [
          {
            id: "eu-14-1",
            name: "Human-in-the-Loop",
            description:
              "Mechanisms exist for human intervention and override of AI decisions.",
          },
          {
            id: "eu-14-2",
            name: "Monitoring Capability",
            description:
              "Operators can monitor AI system behavior during operation.",
          },
        ],
      },
      {
        id: "eu-art-15",
        title: "Article 15 - Accuracy & Robustness",
        description:
          "High-risk AI systems shall achieve appropriate levels of accuracy, robustness, and cybersecurity.",
        controls: [
          {
            id: "eu-15-1",
            name: "Accuracy Metrics",
            description:
              "AI system accuracy is measured and meets declared performance levels.",
          },
          {
            id: "eu-15-2",
            name: "Robustness Testing",
            description:
              "AI system is tested for robustness against errors and adversarial inputs.",
          },
        ],
      },
      {
        id: "eu-art-9",
        title: "Article 9 - Risk Management",
        description:
          "A risk management system shall be established for high-risk AI systems.",
        controls: [
          {
            id: "eu-9-1",
            name: "Risk Identification",
            description:
              "Known and foreseeable risks are identified and analyzed.",
          },
          {
            id: "eu-9-2",
            name: "Risk Mitigation",
            description:
              "Appropriate risk mitigation measures are implemented.",
          },
        ],
      },
      {
        id: "eu-art-12",
        title: "Article 12 - Record Keeping",
        description:
          "High-risk AI systems shall support automatic recording of events (logs).",
        controls: [
          {
            id: "eu-12-1",
            name: "Automatic Logging",
            description:
              "AI system automatically records events and operations.",
          },
          {
            id: "eu-12-2",
            name: "Traceability",
            description:
              "Logs enable traceability of AI system operation throughout its lifecycle.",
          },
        ],
      },
    ],
  },
  {
    framework: "soc2",
    name: "SOC 2",
    sections: [
      {
        id: "soc2-governance",
        title: "AI Model Governance",
        description:
          "Controls for governing AI model development, deployment, and lifecycle management.",
        controls: [
          {
            id: "soc2-gov-1",
            name: "Model Inventory",
            description:
              "All AI models are inventoried with version tracking and ownership.",
          },
          {
            id: "soc2-gov-2",
            name: "Change Management",
            description:
              "Model changes follow a documented change management process.",
          },
        ],
      },
      {
        id: "soc2-data",
        title: "Data Protection",
        description:
          "Controls for protecting data used by and generated by AI systems.",
        controls: [
          {
            id: "soc2-data-1",
            name: "PII Detection & Handling",
            description:
              "PII is detected and handled according to data protection policies.",
          },
          {
            id: "soc2-data-2",
            name: "Data Classification",
            description:
              "Data processed by AI systems is classified and protected accordingly.",
          },
        ],
      },
      {
        id: "soc2-access",
        title: "Access Control",
        description:
          "Controls for managing access to AI systems and their data.",
        controls: [
          {
            id: "soc2-access-1",
            name: "Authentication & Authorization",
            description:
              "Access to AI systems requires proper authentication and authorization.",
          },
          {
            id: "soc2-access-2",
            name: "Least Privilege",
            description:
              "AI system access follows the principle of least privilege.",
          },
        ],
      },
      {
        id: "soc2-monitoring",
        title: "Monitoring & Logging",
        description:
          "Controls for monitoring AI system operations and maintaining audit logs.",
        controls: [
          {
            id: "soc2-mon-1",
            name: "Operational Monitoring",
            description:
              "AI system operations are continuously monitored for anomalies.",
          },
          {
            id: "soc2-mon-2",
            name: "Audit Trail",
            description:
              "Complete audit trails are maintained for all AI system activities.",
          },
        ],
      },
      {
        id: "soc2-incident",
        title: "Incident Response",
        description:
          "Controls for detecting, responding to, and recovering from AI-related incidents.",
        controls: [
          {
            id: "soc2-inc-1",
            name: "Incident Detection",
            description:
              "AI-related security incidents are detected in a timely manner.",
          },
          {
            id: "soc2-inc-2",
            name: "Incident Resolution",
            description:
              "Detected incidents are resolved and documented with root cause analysis.",
          },
        ],
      },
    ],
  },
  {
    framework: "nist_ai_rmf",
    name: "NIST AI Risk Management Framework",
    sections: [
      {
        id: "nist-govern",
        title: "Govern",
        description:
          "Policies, processes, procedures, and practices to map, measure, and manage AI risks.",
        controls: [
          {
            id: "nist-gov-1",
            name: "AI Risk Governance",
            description:
              "Organizational policies for AI risk governance are established.",
          },
          {
            id: "nist-gov-2",
            name: "Accountability Structures",
            description:
              "Roles and responsibilities for AI risk management are defined.",
          },
          {
            id: "nist-gov-3",
            name: "Organizational Culture",
            description:
              "A culture of AI risk awareness is fostered across the organization.",
          },
        ],
      },
      {
        id: "nist-map",
        title: "Map",
        description:
          "Context and risks related to AI systems are understood and documented.",
        controls: [
          {
            id: "nist-map-1",
            name: "Context Establishment",
            description:
              "The context in which AI systems operate is identified and documented.",
          },
          {
            id: "nist-map-2",
            name: "Stakeholder Identification",
            description: "Stakeholders affected by AI systems are identified.",
          },
          {
            id: "nist-map-3",
            name: "Risk Categorization",
            description:
              "AI risks are categorized by type, likelihood, and impact.",
          },
        ],
      },
      {
        id: "nist-measure",
        title: "Measure",
        description:
          "AI risks are analyzed and assessed using appropriate methods and metrics.",
        controls: [
          {
            id: "nist-meas-1",
            name: "Performance Metrics",
            description:
              "Metrics for AI system performance and risk are defined and tracked.",
          },
          {
            id: "nist-meas-2",
            name: "Bias Assessment",
            description:
              "AI systems are assessed for bias and fairness across demographics.",
          },
          {
            id: "nist-meas-3",
            name: "Continuous Monitoring",
            description:
              "AI system behavior is continuously monitored against defined metrics.",
          },
        ],
      },
      {
        id: "nist-manage",
        title: "Manage",
        description:
          "AI risks are prioritized, responded to, and managed based on assessment.",
        controls: [
          {
            id: "nist-man-1",
            name: "Risk Prioritization",
            description:
              "Identified AI risks are prioritized based on impact and likelihood.",
          },
          {
            id: "nist-man-2",
            name: "Risk Response",
            description:
              "Appropriate responses to AI risks are planned and implemented.",
          },
          {
            id: "nist-man-3",
            name: "Risk Communication",
            description:
              "AI risks and management actions are communicated to stakeholders.",
          },
        ],
      },
    ],
  },
  {
    framework: "iso_42001",
    name: "ISO 42001",
    sections: [
      {
        id: "iso-aims",
        title: "AI Management System",
        description:
          "Establish, implement, maintain, and continually improve an AI management system.",
        controls: [
          {
            id: "iso-aims-1",
            name: "Management System Scope",
            description:
              "The scope of the AI management system is defined and documented.",
          },
          {
            id: "iso-aims-2",
            name: "AI Policy",
            description:
              "An AI policy aligned with organizational objectives is established.",
          },
          {
            id: "iso-aims-3",
            name: "Resource Allocation",
            description:
              "Resources needed for the AI management system are determined and provided.",
          },
        ],
      },
      {
        id: "iso-risk",
        title: "Risk Assessment",
        description:
          "Assess risks and opportunities related to the AI management system.",
        controls: [
          {
            id: "iso-risk-1",
            name: "Risk Assessment Process",
            description:
              "A risk assessment process for AI systems is established and applied.",
          },
          {
            id: "iso-risk-2",
            name: "Risk Treatment",
            description:
              "Risk treatment plans are developed and implemented for identified AI risks.",
          },
        ],
      },
      {
        id: "iso-perf",
        title: "Performance Evaluation",
        description:
          "Monitor, measure, analyze, and evaluate the AI management system performance.",
        controls: [
          {
            id: "iso-perf-1",
            name: "Monitoring & Measurement",
            description:
              "AI system performance is monitored and measured against objectives.",
          },
          {
            id: "iso-perf-2",
            name: "Internal Audit",
            description:
              "Internal audits of the AI management system are conducted at planned intervals.",
          },
          {
            id: "iso-perf-3",
            name: "Management Review",
            description:
              "Top management reviews the AI management system at planned intervals.",
          },
        ],
      },
      {
        id: "iso-improve",
        title: "Improvement",
        description:
          "Determine opportunities for improvement and implement necessary actions.",
        controls: [
          {
            id: "iso-improve-1",
            name: "Nonconformity Management",
            description:
              "Nonconformities are identified and corrective actions are taken.",
          },
          {
            id: "iso-improve-2",
            name: "Continual Improvement",
            description:
              "The AI management system is continually improved for suitability and effectiveness.",
          },
        ],
      },
    ],
  },
];

export class AuditReportEngine {
  private config: AuditReportConfig;
  private generatedReports: AuditReport[] = [];

  constructor(config: AuditReportConfig) {
    this.config = config;
  }

  /** Get the control checklist for a compliance framework */
  getFrameworkControls(framework: ComplianceFramework): Control[] {
    const definition = FRAMEWORK_DEFINITIONS.find(
      (d) => d.framework === framework,
    );
    if (!definition) {
      return [];
    }

    const controls: Control[] = [];
    for (const section of definition.sections) {
      for (const ctrl of section.controls) {
        controls.push({
          ...ctrl,
          status: "not_met",
          evidence: [],
          notes: "",
        });
      }
    }
    return controls;
  }

  /** Evaluate a control's status based on available data */
  evaluateControl(control: Control, dataSource: AuditDataSource): Control {
    const evidence: EvidenceItem[] = [];
    let status: Control["status"] = "not_met";

    const controlId = control.id.toLowerCase();

    // Logging / Record-keeping / Audit trail controls
    if (
      controlId.includes("log") ||
      controlId.includes("12") ||
      controlId.includes("mon-2") ||
      controlId.includes("trace")
    ) {
      if (
        dataSource.auditLogs.count > 0 &&
        dataSource.sessionTraces.count > 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "audit_log",
            `${dataSource.auditLogs.count} audit log entries recorded`,
            dataSource.auditLogs.dateRange.start,
          ),
          this.createEvidence(
            "session_trace",
            `${dataSource.sessionTraces.count} session traces captured`,
            dataSource.sessionTraces.dateRange.start,
          ),
        );
      } else if (
        dataSource.auditLogs.count > 0 ||
        dataSource.sessionTraces.count > 0
      ) {
        status = "partial";
        if (dataSource.auditLogs.count > 0) {
          evidence.push(
            this.createEvidence(
              "audit_log",
              `${dataSource.auditLogs.count} audit log entries recorded`,
              dataSource.auditLogs.dateRange.start,
            ),
          );
        }
        if (dataSource.sessionTraces.count > 0) {
          evidence.push(
            this.createEvidence(
              "session_trace",
              `${dataSource.sessionTraces.count} session traces captured`,
              dataSource.sessionTraces.dateRange.start,
            ),
          );
        }
      }
    }
    // Monitoring / Operational monitoring controls
    else if (
      controlId.includes("mon") ||
      controlId.includes("monitor") ||
      controlId.includes("14-2") ||
      controlId.includes("meas-3") ||
      controlId.includes("perf-1")
    ) {
      if (
        dataSource.sessionTraces.count > 0 &&
        dataSource.guardrailEnforcements.count > 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "session_trace",
            `${dataSource.sessionTraces.count} session traces for monitoring`,
            dataSource.sessionTraces.dateRange.start,
          ),
          this.createEvidence(
            "guardrail_enforcement",
            `${dataSource.guardrailEnforcements.count} guardrail enforcements tracked`,
            Date.now(),
          ),
        );
      } else if (dataSource.sessionTraces.count > 0) {
        status = "partial";
        evidence.push(
          this.createEvidence(
            "session_trace",
            `${dataSource.sessionTraces.count} session traces for monitoring`,
            dataSource.sessionTraces.dateRange.start,
          ),
        );
      }
    }
    // PII / Data protection controls
    else if (
      controlId.includes("data") ||
      controlId.includes("pii") ||
      controlId.includes("class")
    ) {
      if (
        dataSource.piiScans.count > 0 &&
        dataSource.piiScans.violations === 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "pii_scan",
            `${dataSource.piiScans.count} PII scans completed with zero violations`,
            Date.now(),
          ),
        );
      } else if (dataSource.piiScans.count > 0) {
        status = "partial";
        evidence.push(
          this.createEvidence(
            "pii_scan",
            `${dataSource.piiScans.count} PII scans completed, ${dataSource.piiScans.violations} violations found`,
            Date.now(),
          ),
        );
      }
    }
    // Incident detection / response controls
    else if (controlId.includes("inc") || controlId.includes("incident")) {
      if (
        dataSource.securityIncidents.count > 0 &&
        dataSource.securityIncidents.resolved ===
          dataSource.securityIncidents.count
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "security_incident",
            `${dataSource.securityIncidents.count} incidents detected and all resolved`,
            Date.now(),
          ),
        );
      } else if (dataSource.securityIncidents.count > 0) {
        status = "partial";
        evidence.push(
          this.createEvidence(
            "security_incident",
            `${dataSource.securityIncidents.count} incidents, ${dataSource.securityIncidents.resolved} resolved`,
            Date.now(),
          ),
        );
      } else if (dataSource.sessionTraces.count > 0) {
        // Monitoring exists but no incidents recorded = met (no incidents to detect)
        status = "met";
        evidence.push(
          this.createEvidence(
            "session_trace",
            "Monitoring active; no security incidents recorded",
            Date.now(),
          ),
        );
      }
    }
    // Risk management / assessment controls
    else if (controlId.includes("risk") || controlId.includes("9-")) {
      if (
        dataSource.guardrailEnforcements.count > 0 &&
        dataSource.securityIncidents.count >= 0 &&
        dataSource.sessionTraces.count > 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "guardrail_enforcement",
            `${dataSource.guardrailEnforcements.count} guardrail enforcements as risk mitigation`,
            Date.now(),
          ),
        );
      } else if (
        dataSource.guardrailEnforcements.count > 0 ||
        dataSource.sessionTraces.count > 0
      ) {
        status = "partial";
        if (dataSource.guardrailEnforcements.count > 0) {
          evidence.push(
            this.createEvidence(
              "guardrail_enforcement",
              `${dataSource.guardrailEnforcements.count} guardrail enforcements`,
              Date.now(),
            ),
          );
        }
      }
    }
    // Access control / authentication controls
    else if (
      controlId.includes("access") ||
      controlId.includes("auth") ||
      controlId.includes("privilege")
    ) {
      if (
        dataSource.auditLogs.count > 0 &&
        dataSource.configChanges.count > 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "audit_log",
            `${dataSource.auditLogs.count} audit logs tracking access`,
            dataSource.auditLogs.dateRange.start,
          ),
          this.createEvidence(
            "config_setting",
            `${dataSource.configChanges.count} config changes tracked`,
            Date.now(),
          ),
        );
      } else if (dataSource.auditLogs.count > 0) {
        status = "partial";
        evidence.push(
          this.createEvidence(
            "audit_log",
            `${dataSource.auditLogs.count} audit logs tracking access`,
            dataSource.auditLogs.dateRange.start,
          ),
        );
      }
    }
    // Governance / policy / management / documentation controls
    else if (
      controlId.includes("gov") ||
      controlId.includes("policy") ||
      controlId.includes("aims") ||
      controlId.includes("doc") ||
      controlId.includes("13-1") ||
      controlId.includes("scope") ||
      controlId.includes("resource")
    ) {
      if (
        dataSource.configChanges.count > 0 &&
        dataSource.auditLogs.count > 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "config_setting",
            `${dataSource.configChanges.count} configuration changes documented`,
            Date.now(),
          ),
          this.createEvidence(
            "audit_log",
            `${dataSource.auditLogs.count} audit log entries supporting governance`,
            dataSource.auditLogs.dateRange.start,
          ),
        );
      } else if (
        dataSource.configChanges.count > 0 ||
        dataSource.auditLogs.count > 0
      ) {
        status = "partial";
        if (dataSource.configChanges.count > 0) {
          evidence.push(
            this.createEvidence(
              "config_setting",
              `${dataSource.configChanges.count} configuration changes documented`,
              Date.now(),
            ),
          );
        }
      }
    }
    // Human oversight / interpretability / transparency
    else if (
      controlId.includes("human") ||
      controlId.includes("14-1") ||
      controlId.includes("13-2") ||
      controlId.includes("interpret")
    ) {
      if (
        dataSource.guardrailEnforcements.count > 0 &&
        dataSource.guardrailEnforcements.blocked > 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "guardrail_enforcement",
            `${dataSource.guardrailEnforcements.blocked} actions blocked by guardrails (human oversight)`,
            Date.now(),
          ),
        );
      } else if (dataSource.guardrailEnforcements.count > 0) {
        status = "partial";
        evidence.push(
          this.createEvidence(
            "guardrail_enforcement",
            `${dataSource.guardrailEnforcements.count} guardrail enforcements active`,
            Date.now(),
          ),
        );
      }
    }
    // Accuracy / testing / performance / bias / metrics
    else if (
      controlId.includes("accur") ||
      controlId.includes("robust") ||
      controlId.includes("15-") ||
      controlId.includes("meas") ||
      controlId.includes("bias") ||
      controlId.includes("perf")
    ) {
      if (
        dataSource.sessionTraces.count > 0 &&
        dataSource.guardrailEnforcements.count > 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "session_trace",
            `${dataSource.sessionTraces.count} session traces for performance evaluation`,
            dataSource.sessionTraces.dateRange.start,
          ),
        );
      } else if (dataSource.sessionTraces.count > 0) {
        status = "partial";
        evidence.push(
          this.createEvidence(
            "session_trace",
            `${dataSource.sessionTraces.count} session traces available`,
            dataSource.sessionTraces.dateRange.start,
          ),
        );
      }
    }
    // Improvement / nonconformity / change / communication / stakeholder / culture
    else {
      if (
        dataSource.configChanges.count > 0 &&
        dataSource.auditLogs.count > 0
      ) {
        status = "met";
        evidence.push(
          this.createEvidence(
            "config_setting",
            `${dataSource.configChanges.count} config changes supporting improvement`,
            Date.now(),
          ),
        );
      } else if (
        dataSource.auditLogs.count > 0 ||
        dataSource.configChanges.count > 0
      ) {
        status = "partial";
        if (dataSource.auditLogs.count > 0) {
          evidence.push(
            this.createEvidence(
              "audit_log",
              `${dataSource.auditLogs.count} audit log entries`,
              dataSource.auditLogs.dateRange.start,
            ),
          );
        }
      }
    }

    return {
      ...control,
      status,
      evidence: this.config.includeEvidence ? evidence : [],
      notes:
        status === "met"
          ? "Control requirements are satisfied."
          : status === "partial"
            ? "Control is partially met; additional evidence or action needed."
            : "Control requirements are not met; remediation required.",
    };
  }

  /** Generate a full compliance report for a framework */
  generateReport(
    framework: ComplianceFramework,
    dataSource: AuditDataSource,
    period: { start: number; end: number },
  ): AuditReport {
    const definition = FRAMEWORK_DEFINITIONS.find(
      (d) => d.framework === framework,
    );
    if (!definition) {
      throw new Error(`Unknown compliance framework: ${framework}`);
    }

    const sections: ReportSection[] = definition.sections.map((section) => {
      const evaluatedControls = section.controls
        .map((ctrl) => ({
          ...ctrl,
          status: "not_met" as Control["status"],
          evidence: [] as EvidenceItem[],
          notes: "",
        }))
        .map((ctrl) => this.evaluateControl(ctrl, dataSource));

      const score = this.calculateSectionScore(evaluatedControls);

      return {
        id: section.id,
        title: section.title,
        description: section.description,
        controls: evaluatedControls,
        score,
        status: this.scoreToStatus(score),
      };
    });

    const overallScore =
      sections.length > 0
        ? Math.round(
            sections.reduce((sum, s) => sum + s.score, 0) / sections.length,
          )
        : 0;

    const report: AuditReport = {
      id: `report-${framework}-${Date.now()}`,
      framework,
      organizationName: this.config.organizationName,
      generatedAt: Date.now(),
      period,
      sections,
      overallScore,
      status: this.scoreToStatus(overallScore),
      gaps: [],
      recommendations: [],
    };

    report.gaps = this.identifyGaps(report);
    report.recommendations = this.generateRecommendations(report);

    this.generatedReports.push(report);

    return report;
  }

  /** Assess overall compliance posture across all configured frameworks */
  assessPosture(dataSource: AuditDataSource): CompliancePosture {
    const now = Date.now();
    const period = { start: now - 30 * 24 * 60 * 60 * 1000, end: now };
    const frameworks = new Map<ComplianceFramework, PostureScore>();

    let totalControls = 0;
    let metControls = 0;
    let partialControls = 0;
    let notMetControls = 0;

    for (const fw of this.config.frameworks) {
      const report = this.generateReport(fw, dataSource, period);

      let fwMet = 0;
      let fwPartial = 0;
      let fwNotMet = 0;

      for (const section of report.sections) {
        for (const control of section.controls) {
          totalControls++;
          if (control.status === "met") {
            fwMet++;
            metControls++;
          } else if (control.status === "partial") {
            fwPartial++;
            partialControls++;
          } else if (control.status === "not_met") {
            fwNotMet++;
            notMetControls++;
          }
        }
      }

      frameworks.set(fw, {
        framework: fw,
        score: report.overallScore,
        status: report.status,
        gaps: report.gaps.length,
        lastAssessed: now,
      });
    }

    return {
      frameworks,
      totalControls,
      metControls,
      partialControls,
      notMetControls,
      lastAssessed: now,
    };
  }

  /** Identify compliance gaps from a report */
  identifyGaps(report: AuditReport): ComplianceGap[] {
    const gaps: ComplianceGap[] = [];

    for (const section of report.sections) {
      for (const control of section.controls) {
        if (control.status === "not_met" || control.status === "partial") {
          gaps.push({
            controlId: control.id,
            framework: report.framework,
            severity: control.status === "not_met" ? "high" : "medium",
            description: `${control.name}: ${control.description}`,
            remediation:
              control.status === "not_met"
                ? `Implement controls to satisfy ${control.name}. Collect evidence of ${control.description.toLowerCase()}`
                : `Strengthen existing controls for ${control.name}. Additional evidence or processes needed.`,
          });
        }
      }
    }

    return gaps;
  }

  /** Export a report as Markdown */
  exportToMarkdown(report: AuditReport): string {
    const lines: string[] = [];

    lines.push(
      `# Compliance Report: ${this.getFrameworkName(report.framework)}`,
    );
    lines.push("");
    lines.push(`**Organization:** ${report.organizationName}`);
    lines.push(`**Generated:** ${new Date(report.generatedAt).toISOString()}`);
    lines.push(
      `**Period:** ${new Date(report.period.start).toISOString()} to ${new Date(report.period.end).toISOString()}`,
    );
    lines.push(`**Overall Score:** ${report.overallScore}/100`);
    lines.push(`**Status:** ${report.status}`);
    lines.push("");

    for (const section of report.sections) {
      lines.push(`## ${section.title}`);
      lines.push("");
      lines.push(`*${section.description}*`);
      lines.push("");
      lines.push(
        `**Section Score:** ${section.score}/100 | **Status:** ${section.status}`,
      );
      lines.push("");

      for (const control of section.controls) {
        const statusIcon =
          control.status === "met"
            ? "✅"
            : control.status === "partial"
              ? "⚠️"
              : control.status === "not_met"
                ? "❌"
                : "➖";
        lines.push(`### ${statusIcon} ${control.name}`);
        lines.push("");
        lines.push(control.description);
        lines.push("");
        lines.push(
          `**Status:** ${control.status} | **Notes:** ${control.notes}`,
        );

        if (control.evidence.length > 0) {
          lines.push("");
          lines.push("**Evidence:**");
          for (const ev of control.evidence) {
            lines.push(`- ${ev.description} (${ev.type})`);
          }
        }
        lines.push("");
      }
    }

    if (report.gaps.length > 0) {
      lines.push("## Compliance Gaps");
      lines.push("");
      for (const gap of report.gaps) {
        lines.push(`- **[${gap.severity.toUpperCase()}]** ${gap.description}`);
        lines.push(`  - Remediation: ${gap.remediation}`);
      }
      lines.push("");
    }

    if (report.recommendations.length > 0) {
      lines.push("## Recommendations");
      lines.push("");
      for (const rec of report.recommendations) {
        lines.push(`- ${rec}`);
      }
      lines.push("");
    }

    return lines.join("\n");
  }

  /** Export a report as CSV */
  exportToCSV(report: AuditReport): string {
    const rows: string[] = [];
    rows.push(
      "Section,Control ID,Control Name,Status,Score,Evidence Count,Notes",
    );

    for (const section of report.sections) {
      for (const control of section.controls) {
        const escapedNotes = `"${control.notes.replace(/"/g, '""')}"`;
        const escapedName = `"${control.name.replace(/"/g, '""')}"`;
        rows.push(
          `"${section.title}",${control.id},${escapedName},${control.status},${section.score},${control.evidence.length},${escapedNotes}`,
        );
      }
    }

    return rows.join("\n");
  }

  /** Export a report as formatted JSON */
  exportToJSON(report: AuditReport): string {
    return JSON.stringify(report, null, 2);
  }

  /** Get engine metrics */
  getMetrics(): AuditReportMetrics {
    const frameworksCovered = new Set(
      this.generatedReports.map((r) => r.framework),
    ).size;
    const totalGaps = this.generatedReports.reduce(
      (sum, r) => sum + r.gaps.length,
      0,
    );
    const avgScore =
      this.generatedReports.length > 0
        ? Math.round(
            this.generatedReports.reduce((sum, r) => sum + r.overallScore, 0) /
              this.generatedReports.length,
          )
        : 0;

    return {
      reportsGenerated: this.generatedReports.length,
      frameworksCovered,
      totalGapsIdentified: totalGaps,
      avgComplianceScore: avgScore,
      lastReportGenerated:
        this.generatedReports.length > 0
          ? this.generatedReports[this.generatedReports.length - 1].generatedAt
          : null,
    };
  }

  private calculateSectionScore(controls: Control[]): number {
    if (controls.length === 0) return 0;

    let score = 0;
    for (const control of controls) {
      if (control.status === "met") {
        score += 100;
      } else if (control.status === "partial") {
        score += 50;
      } else if (control.status === "not_applicable") {
        score += 100;
      }
      // not_met = 0
    }

    return Math.round(score / controls.length);
  }

  private scoreToStatus(
    score: number,
  ): "compliant" | "partial" | "non_compliant" {
    if (score >= 80) return "compliant";
    if (score >= 50) return "partial";
    return "non_compliant";
  }

  private getFrameworkName(framework: ComplianceFramework): string {
    const definition = FRAMEWORK_DEFINITIONS.find(
      (d) => d.framework === framework,
    );
    return definition?.name ?? framework;
  }

  private generateRecommendations(report: AuditReport): string[] {
    const recommendations: string[] = [];

    const notMetControls = report.sections.flatMap((s) =>
      s.controls.filter((c) => c.status === "not_met"),
    );
    const partialControls = report.sections.flatMap((s) =>
      s.controls.filter((c) => c.status === "partial"),
    );

    if (notMetControls.length > 0) {
      recommendations.push(
        `Address ${notMetControls.length} unmet control(s) as a priority to improve compliance posture.`,
      );
    }

    if (partialControls.length > 0) {
      recommendations.push(
        `Strengthen ${partialControls.length} partially met control(s) by collecting additional evidence.`,
      );
    }

    if (report.overallScore < 50) {
      recommendations.push(
        "Overall compliance score is below 50%. Conduct a comprehensive review of all control areas.",
      );
    }

    if (report.overallScore >= 80) {
      recommendations.push(
        "Maintain current compliance posture through continuous monitoring and periodic re-assessment.",
      );
    }

    return recommendations;
  }

  private createEvidence(
    type: EvidenceItem["type"],
    description: string,
    timestamp: number,
  ): EvidenceItem {
    return {
      id: `ev-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      type,
      description,
      reference: `${type}://${Date.now()}`,
      timestamp,
      data: {},
    };
  }
}
